### ISSUE TITLE
Unable to get title from the https link

### ISSUE THREAD

**Issue by chaica** [chaica/lobsters#2]
Hi,

While posting a link, you have a button to automatically fetch the title of the link. It seems it does not work with https link. No idea why.

Regards,
Carl Chenet

**Comment by xcombelle** [comment]
I checked on https://fr.wikipedia.org and looks like I can fetch some https link. However checked the code and at https://github.com/chaica/lobsters/blob/master/extras/sponge.rb#L90 it rejects the ipv6  addresses

**Comment by chaica** [comment]
I can not fetch this link : https://tuxicoman.jesuislibre.net/2015/08/mettre-a-jour-cyanogen-sur-un-appareil-android-chiffre.html
can't get this link neither : https://mytux.fr/contact.html

But indeed wikipedia works... I'm not sure why

**Comment by xcombelle** [comment]
Oh there is another condition in this code, it forbid local address IP for security reasons

**Comment by xcombelle** [comment]
Concerning the tuxicoman.jesuislibre.net I think I found what happen. The server use [Server Name Indication](https://en.wikipedia.org/wiki/Server_Name_Indication) but Ruby Net::HTTP library use always use SNI even when the "server name" is an IP, so the server is confused. 
not using SNI (for this particular case) or setting the sever name for SNI would solve the problem
but as the absence of answer to this  question show (no answer) https://stackoverflow.com/questions/25200675/sni-support-in-rubys-net-http-if-there-is-no-route-to-hostname it looks not possible to set server_hostname in ruby

I succeed to reproduce the behaviour with the following code (in python)
```
from functools import partial
import socket
import ssl
HOST ="81.240.22.197"
PORT = 443
sock = socket.socket()
sock.connect((HOST, PORT))
context = ssl.create_default_context(ssl.Purpose.CLIENT_AUTH)
sock = context.wrap_socket(sock, 
server_hostname="81.240.22.197"
)
sock.write(b"GET /2015/08/mettre-a-jour-cyanogen-sur-un-appareil-android-chiffre.html HTTP/1.1\r\nHost: tuxicoman.jesuislibre.net\r\nAccept: */*\r\nUser-Agent: Ruby\r\nConnection: close\r\n\r\n")
for l in iter(partial(sock.read),b''):
    print(l,end='')
#print error 400 as ruby does
```

**Comment by chaica** [comment]
Ok really good catch, so I just checked on the current lobster.rs engine and it's the same. I guess it's a won't fix because it's related to the Ruby library.

It does not work with the domain names related to the local IP addresses because of security and does not work if the remote server uses SNI because of the Ruby library. Feel free to reopen if it does not seem right
